### ISSUE TITLE
Class properties are not present in API Reference output

### ISSUE THREAD

**Issue by yck011522** [compas-dev/sphinx_compas_theme#21]
I'm working on compas_fab and notice that class properties are not in the docs output. I discovered this was briefly discussed among @gonzalocasas and @tomvanmele in 2022. 

I believe many classes have now grown to have quite a number of read-only properties that are created by `@property` decorator. They are not private features but are intended to be publicly exposed to users. Would it make sense to add the properties back to the doc? 

Here is an example of the class file I'm working on that triggered me: https://github.com/compas-dev/compas_fab/blob/main/src/compas_fab/robots/reachability_map/reachability_map.py#L101-L119

The current way of writing the properties docstring in the class level docstring is not recommended by the [NumPy Style defined in the Contributors Guide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#:~:text=Properties%20created%20with%20the%20%60%60%40property%60%60%20decorator%20should%20be%20documented%0A%20%20%20%20in%20the%20property%27s%20getter%20method.),

--------------------------
              These properties are not present in the doc output. At least locally, did I miss some config? I have latest versions of both sphinx and our sphinx theme.

![image](https://user-images.githubusercontent.com/933277/148189725-92eb003a-a065-4f06-8084-c7f8abc80dc9.png)

_Originally posted by @gonzalocasas in https://github.com/compas-dev/compas/pull/958#discussion_r778646734_

**Comment by tomvanmele** [comment]
hi victor,

in the "old" theme you indeed have to list (and document) those properties in the "Attributes" section of the class level docstring. the reason for this is that we never got them to render properly in the automated way...

if that doesn't work for you, please feel free to propose an update to the theme.

however, with COMPAS 2.0 we have started to use the PyData theme so it might be worth checking this out as well.

https://compas.dev/compas/latest/userguide/index.html
https://pydata-sphinx-theme.readthedocs.io/en/stable/

**Comment by yck011522** [comment]
Hi Tom, thanks for the explanation. I don't know how to program Sphinx themes. But as you say, if it were tried in the past and the current theme does not render automatically, I would then accept that as a limitation.
  
But are you saying that the PyData Theme will automatically render the properties as "read-only" attributes?

**Comment by tomvanmele** [comment]
no, unfortunately, as far as a i know, there is not a single sphinx theme that automatically deals with this kind of thing. nor with `classmethod`, `staticmethod` etc. you still have to handle the differentiation between these things manually...

however, since PyData is the theme used also by Numpy, there is a reasonable chance that something like this might be added in the future.

**Comment by yck011522** [comment]
I see. Thank you for your reply.
