### ISSUE TITLE
Index (`genindex`) is empty on the compaspkg theme

### ISSUE THREAD

**Issue by fleischp** [compas-dev/sphinx_compas_theme#6]
The theme for compas packages seems to be ignoring the index generation (`genindex` directive/reference). The output in `genindex.html` is an empty document. 

For reference, the same rst documents generate an index properly when using the default sphinx theme.

Compare this:
![image](https://user-images.githubusercontent.com/35273829/94654067-d1372b80-02fc-11eb-85fb-fd10533f14af.png)

To this output when the `compaspkg` theme is selected:
![image](https://user-images.githubusercontent.com/35273829/94654085-d85e3980-02fc-11eb-8c9d-1aa47459a3fe.png)

**Comment by brgcode** [comment]
sorry for the late reply. i am not sure why that is the case, but am looking into it...

**Comment by brgcode** [comment]
this is solved since `0.13`
