### ISSUE TITLE
Bundle _templates in the pip installable theme

### ISSUE THREAD

**Issue by fleischp** [compas-dev/sphinx_compas_theme#7]
There are 4 `_templates` for autosummary that are missing in this package, and once the theme is pip-installed the output misses a few things. In the case of using  autosummary on a module, the classes will be included but their members will not.

Ideally these templates should be bundled in this pip installable package.

**Comment by brgcode** [comment]
there seems to be no (documented) way of doing this. however, i will update the COMPAS package template such that the files are included there.

@gonzalocasas any other ideas?

**Comment by gonzalocasas** [comment]
I looked around, but also couldn't find any way to bundle these. And I didn't find any other theme that would do anything related to that. Are we misusing autosummary perhaps?

**Comment by brgcode** [comment]
as far as i know this is meant to be "up to the developer". however, i noticed that our package templates include those autosummary stubs. so perhaps the easiest solution is to just use the templates, no?

**Comment by brgcode** [comment]
this is solved since version `0.13`
